version: "3"
services:
  topdeck-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MYSQL_DATABASE=sentinel
      - MYSQL_USER=sentinel
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
        - 3306:3306